### ISSUE TITLE
Version bump

### ISSUE THREAD

**Issue by finwo** [levelgraph/levelgraph#190]
Current merged PRs in the master branch that are not part of a release:
- #171
- #187 
- #188 
- #189 
- #191 

Changes in the mentioned pull requests:
- Updated readme logo reference
- Added `tmp` dependency
- Fix hexastore link in readme
- Replaced [level-browserify](https://npmjs.com/package/level-browserify) by [level](https://npmjs.com/package/level), due to level-browserify not installing on newer node versions anymore and level now supporting browser environments
- Stream closing in `test/triple_unicode_store_spec` and `test/triple_store_spec` are now done on the `end` instead of the `close` event due to a double-trigger of the `end` event. (this may warrant another bugfix in the future)
- Updated dev dependencies
  - [level-sublevel](https://npmjs.com/package/level-sublevel)
  - [multilevel](https://npmjs.com/package/multilevel)
  - [osenv](https://npmjs.com/package/osenv)
  - [setimmediate](https://npmjs.com/package/setimmediate)
  - [tmp](https://npmjs.com/package/tmp)
- Replaced range notation during the opening of read streams, changed from `start` and `end` to `gte` and `lte`
- Added CI based on github-actions, making new pull requests show the testing status on a known platform again

**Comment by finwo** [comment]
@mcollina So, something like this for requesting a new release?

**Comment by mcollina** [comment]
let's do a major. Most of the changes in the dependencies requires a major update.

I would prefer to have CI fixed and a Node version support matrix included.

**Comment by finwo** [comment]
Would you prefer to fix coveralls or set up githb actions?

**Comment by mcollina** [comment]
Just drop coveralls. I just care of having a CI running.

**Comment by finwo** [comment]
Assuming the unit tests pass and the version was bumped.. Would you want the package to automatically deploy when the new version number hits the master branch?

That'd look something like this in the action file, assuming you'd want it to only run on master and once the tests have passed:

```yml
  publish:
    needs: unit-tests
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: rm -rf node_modules
      - run: npm ci
      - run: npm run build --if-present
      - run: if [ $(npm view $(node -p "require('./package.json').name") version) != $(node -p "require('./package.json').version") ]; then npm publish ; fi
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
```
